In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_excel("Pandas assignment netflix file.xlsx")

In [4]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."
...,...,...,...,...,...,...,...,...,...,...,...
8775,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers"
8776,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies"
8777,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies"
8778,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies"
8779,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals"

In [5]:
#First five rows
data.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."

In [6]:
#last 5 rows
data.tail(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
8775,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers"
8776,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies"
8777,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies"
8778,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies"
8779,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals"

In [19]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."
...,...,...,...,...,...,...,...,...,...,...,...
8775,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers"
8776,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies"
8777,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies"
8778,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies"
8779,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals"

In [26]:
#B.
data.count

<bound method DataFrame.count of      show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
...      ...      ...                    ...              ...
8775   s8803    Movie                 Zodiac    David Fincher
8776   s8804  TV Show            Zombie Dumb              NaN
8777   s8805    Movie             Zombieland  Ruben Fleischer
8778   s8806    Movie                   Zoom     Peter Hewitt
8779   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                   NaN  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8775  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8776                                                NaN            NaN
8777  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8778  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8779  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min
1     September 24, 2021          2021  TV-MA  2 Seasons
2     September 24, 2021          2021  TV-MA   1 Season
3     September 24, 2021          2021  TV-MA   1 Season
4     September 24, 2021          2021  TV-MA  2 Seasons
...                  ...           ...    ...        ...
8775   November 20, 2019          2007      R    158 min
8776        July 1, 2019          2018  TV-Y7  2 Seasons
8777    November 1, 2019          2009      R     88 min
8778    January 11, 2020          2006     PG     88 min
8779       March 2, 2019          2015  TV-14    111 min

                                              listed_in
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8775                     Cult Movies, Dramas, Thrillers
8776             Kids' TV, Korean TV Shows, TV Comedies
8777                            Comedies, Horror Movies
8778                 Children & Family Movies, Comedies
8779     Dramas, International Movies, Music & Musicals

[8780 rows x 11 columns]>

In [25]:
#C 
data.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='object')

In [27]:
#D.
data.describe()

       release_year
count   8780.000000
mean    2014.178474
std        8.827938
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [31]:
#E.
data.nunique()

show_id         8780
type               2
title           8780
director        4516
cast            7671
country          745
date_added      1765
release_year      74
rating            14
duration         220
listed_in        514
dtype: int64

In [33]:
#F.
data.isnull().mean()*100

show_id          0.000000
type             0.000000
title            0.000000
director        29.954442
cast             9.384966
country          9.430524
date_added       0.113895
release_year     0.000000
rating           0.045558
duration         0.000000
listed_in        0.000000
dtype: float64

In [36]:
#G.
data.dropna(subset=['director'],inplace=True)

In [37]:
print(data)

     show_id     type                             title  \
0         s1    Movie              Dick Johnson Is Dead
2         s3  TV Show                         Ganglands
5         s6  TV Show                     Midnight Mass
6         s7    Movie  My Little Pony: A New Generation
7         s8    Movie                           Sankofa
...      ...      ...                               ...
8774   s8802    Movie                           Zinzana
8775   s8803    Movie                            Zodiac
8777   s8805    Movie                        Zombieland
8778   s8806    Movie                              Zoom
8779   s8807    Movie                            Zubaan

                            director  \
0                    Kirsten Johnson
2                    Julien Leclercq
5                      Mike Flanagan
6     Robert Cullen, JosÃ© Luis Ucha
7                       Haile Gerima
...                              ...
8774                 Majid Al Ansari
8775                   David Fincher
8777                 Ruben Fleischer
8778                    Peter Hewitt
8779                     Mozez Singh

                                                   cast  \
0                                                   NaN
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
5     Kate Siegel, Zach Gilford, Hamish Linklater, H...
6     Vanessa Hudgens, Kimiko Glenn, James Marsden, ...
7     Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
...                                                 ...
8774  Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...
8775  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
8777  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
8778  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
8779  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...

                                                country          date_added  \
0                                         United States  September 25, 2021
2                                                   NaN  September 24, 2021
5                                                   NaN  September 24, 2021
6                                                   NaN  September 24, 2021
7     United States, Ghana, Burkina Faso, United Kin...  September 24, 2021
...                                                 ...                 ...
8774                       United Arab Emirates, Jordan       March 9, 2016
8775                                      United States   November 20, 2019
8777                                      United States    November 1, 2019
8778                                      United States    January 11, 2020
8779                                              India       March 2, 2019

      release_year rating  duration  \
0             2020  PG-13    90 min
2             2021  TV-MA  1 Season
5             2021  TV-MA  1 Season
6             2021     PG    91 min
7             1993  TV-MA   125 min
...            ...    ...       ...
8774          2015  TV-MA    96 min
8775          2007      R   158 min
8777          2009      R    88 min
8778          2006     PG    88 min
8779          2015  TV-14   111 min

                                              listed_in
0                                         Documentaries
2     Crime TV Shows, International TV Shows, TV Act...
5                    TV Dramas, TV Horror, TV Mysteries
6                              Children & Family Movies
7      Dramas, Independent Movies, International Movies
...                                                 ...
8774            Dramas, International Movies, Thrillers
8775                     Cult Movies, Dramas, Thrillers
8777                            Comedies, Horror Movies
8778                 Children & Family Movies, Comedies
8779     Dramas, International Movies, Music & Musicals

[6150 rows x 11 columns]

In [38]:
# Number of rows has come down [6150 rows x 11 columns]

In [39]:
#H
Germany=data[data['country'].isin(['Germany', 'West Germany'])]

In [40]:
print(Germany)

     show_id   type                                       title  \
705     s706  Movie                              Biking Borders
1030   s1032  Movie                               Into the Beat
1196   s1199  Movie        RebellComedy: Straight Outta the Zoo
1250   s1253  Movie                        How to Be Really Bad
1265   s1268  Movie                                    Who Am I
1590   s1593  Movie                         Christmas Crossfire
1740   s1743  Movie                        Felix Lobrecht: Hype
2053   s2056  Movie                 Freaks â€“ You're One of Us
2147   s2151  Movie            Berlin, Berlin: Lolle on the Run
2182   s2186  Movie              Latte and the Magic Waterstone
2667   s2672  Movie                                 Rising High
2772   s2777  Movie                           Making Unorthodox
2890   s2896  Movie                              System Crasher
2909   s2915  Movie                                  Isi & Ossi
3667   s3673  Movie                           Kidnapping Stella
3730   s3736  Movie                        Right Here Right Now
3762   s3768  Movie                               Rock My Heart
3767   s3773  Movie                               Alles ist gut
4391   s4403  Movie                                    Lommbock
4831   s4844  Movie                             Pedal the World
4859   s4872  Movie                                   My Fuhrer
4903   s4916  Movie                     Enissa Amani: Ehrenwort
4999   s5012  Movie                            Schubert In Love
5043   s5056  Movie                        Expedition Happiness
5094   s5107  Movie               Bibi & Tina: Tohuwabohu Total
5177   s5190  Movie                     Pettersson and Findus 2
5293   s5307  Movie     Offline - Das leben ist kein bonuslevel
5512   s5527  Movie                                 Bibi & Tina
5513   s5528  Movie                              Bibi & Tina II
5514   s5529  Movie              Bibi & Tina: Girls Versus Boys
5585   s5601  Movie                               A Heavy Heart
5597   s5613  Movie                           Hitler - A Career
5617   s5633  Movie                              Berlin Calling
5619   s5635  Movie                                      Stereo
5620   s5636  Movie                We Are Young. We Are Strong.
5648   s5665  Movie                        3 TÃ¼rken & ein Baby
5701   s5718  Movie                 Dieter Nuhr: Nuhr in Berlin
6232   s6260  Movie  Beak & Brain: Genius Birds From Down Under
6531   s6559  Movie                             Dancing Quietly
6621   s6649  Movie                                  Dream Boat
6709   s6737  Movie                                    Familiye
6778   s6806  Movie                              Friend Request
7309   s7337  Movie                             Look Who's Back
8369   s8397  Movie                         The Lives of Others
8413   s8441  Movie                             The NSU-Complex
8426   s8454  Movie                               The Physician

                                   director  \
705                                Max Jabs
1030                     Stefan Westerwelle
1196                       Ladislaus Kiraly
1250                            Marco Petry
1265                          Baran bo Odar
1590                            Detlev Buck
1740                        Jan-Peter Horns
2053                           Felix Binder
2147                  Franziska Meyer Price
2182               Regina Welker, Nina Wels
2667                           CÃ¼neyt Kaya
2772                       Marlene Melchior
2890                       Nora Fingscheidt
2909                          Oliver Kienle
3667                          Thomas Sieben
3730                             Jakob Lass
3762                      Hanno Olderdissen
3767                           Eva Trobisch
4391                      Christian ZÃ¼bert
4831                           Felix Starck
4859                              Dani Levy
4903                              Max Amini
4999                           Lars BÃ¼chel
5043                           Selima Taibi
5094                            Detlev Buck
5177                       Ali Samadi Ahadi
5293                        Florian Schnell
5512                            Detlev Buck
5513                            Detlev Buck
5514                            Detlev Buck
5585                          Thomas Stuber
5597  Joachim Fest, Christian Herrendoerfer
5617                          Hannes StÃ¶hr
5619                   Maximilian Erlenwein
5620                         Burhan Qurbani
5648                           Sinan AkkuÅŸ
5701                         Volker Weicker
6232             Volker Arzt, Angelika Sigl
6531                      Philipp Eichholtz
6621               Tristan Ferland Milewski
6709         Sedat Kirtan, Kubilay Sarikaya
6778                        Simon Verhoeven
7309                           David Wnendt
8369       Florian Henckel von Donnersmarck
8413                Stefan Aust, Dirk Laabs
8426                        Philipp StÃ¶lzl

                                                   cast       country  \
705                              Max Jabs, Nono Konopka       Germany
1030  Alexandra Pfeifer, Yalany Marschner, Trystan P...       Germany
1196  Khalid Bounouar, Alain Frei, Babak Ghassim, Be...       Germany
1250  Emma Bading, Janina Fautz, Ludwig Simon, Samue...       Germany
1265  Tom Schilling, Elyas M'Barek, Wotan Wilke MÃ¶h...       Germany
1590  Kostja Ullmann, Alli Neumann, Sascha Alexander...       Germany
1740                                     Felix Lobrecht       Germany
2053  Cornelia GrÃ¶schel, Tim Oliver Schultz, Wotan ...       Germany
2147  Felicitas Woll, Janina Uhse, Jan Sosniok, Matt...       Germany
2182                  Ashley Bornancin, Carter Hastings       Germany
2667  David Kross, Frederick Lau, Janina Uhse, Anne ...       Germany
2772                                                NaN       Germany
2890  Helena Zengel, Albrecht Schuch, Gabriela Maria...       Germany
2909  Lisa Vicari, Dennis Mojen, Walid Al-Atiyat, Ch...       Germany
3667   Max von der Groeben, Jella Haase, Clemens Schick       Germany
3730  Niklas Bruhn, David SchÃ¼tter, Tinka Furst, Co...       Germany
3762  Lena Klenke, Dieter Hallervorden, Emilio Sakra...       Germany
3767  Aenne Schwarz, Andreas DÃ¶hler, Hans LÃ¶w, Til...       Germany
4391  Lucas Gregorowicz, Moritz Bleibtreu, Louis Hof...       Germany
4831                                       Felix Starck       Germany
4859  Helge Schneider, Ulrich MÃ¼he, Sylvester Groth...       Germany
4903                                       Enissa Amani       Germany
4999  Olaf Schubert, Mario Adorf, Marie Leuenberger,...       Germany
5043                         Selima Taibi, Felix Starck       Germany
5094  Lina Larissa Strahl, Lisa-Marie Koroll, Louis ...       Germany
5177  Stefan Kurt, Marianne SÃ¤gebrecht, Max Herbrec...       Germany
5293  Moritz Jahn, Mala Emde, Ugur Ekeroglu, David S...       Germany
5512  Lina Larissa Strahl, Lisa-Marie Koroll, Louis ...       Germany
5513  Lina Larissa Strahl, Lisa-Marie Koroll, Louis ...       Germany
5514  Lina Larissa Strahl, Lisa-Marie Koroll, Tilman...       Germany
5585  Peter Kurth, Lena Lauzemis, Lina Wendel, Edin ...       Germany
5597                                                NaN  West Germany
5617  Paul Kalkbrenner, Rita Lengyel, Corinna Harfou...       Germany
5619  JÃ¼rgen Vogel, Moritz Bleibtreu, Petra Schmidt...       Germany
5620  Jonas Nay, Trang Le Hong, Devid Striesow, Joel...       Germany
5648  Kostja Ullmann, Eko Fresh, Kida Khodr Ramadan,...       Germany
5701                                        Dieter Nuhr       Germany
6232                                                NaN       Germany
6531  Martina SchÃ¶ne-Radunski, Hans-Heinrich Hardt,...       Germany
6621                                                NaN       Germany
6709  Kubilay Sarikaya, Arnel Taci, Muhammed Kirtan,...       Germany
6778  Alycia Debnam-Carey, William Moseley, Connor P...       Germany
7309  Oliver Masucci, Fabian Busch, Christoph Maria ...       Germany
8369  Ulrich MÃ¼he, Martina Gedeck, Sebastian Koch, ...       Germany
8413                                                NaN       Germany
8426  Tom Payne, Ben Kingsley, Stellan SkarsgÃ¥rd, O...       Germany

             date_added  release_year rating duration  \
705       June 16, 2021          2019  TV-14   89 min
1030     April 16, 2021          2020  TV-14  102 min
1196     March 16, 2021          2021  TV-MA   74 min
1250      March 1, 2021          2018  TV-14  100 min
1265  February 26, 2021          2014  TV-MA  102 min
1590   December 4, 2020          2020  TV-MA  106 min
1740   November 3, 2020          2020  TV-MA   60 min
2053  September 2, 2020          2020  TV-MA   93 min
2147     August 7, 2020          2020  TV-MA   82 min
2182      July 31, 2020          2020   TV-Y   83 min
2667     April 17, 2020          2020  TV-MA   95 min
2772     March 26, 2020          2020   TV-G   21 min
2890  February 21, 2020          2020  TV-MA  120 min
2909  February 14, 2020          2020  TV-MA  113 min
3667      July 12, 2019          2019  TV-MA   90 min
3730      June 16, 2019          2018  TV-MA   91 min
3762       June 7, 2019          2019  TV-PG  110 min
3767       June 6, 2019          2019  TV-MA   90 min
4391   November 9, 2018          2017  TV-MA  106 min
4831       June 1, 2018          2015  TV-MA   85 min
4859        May 7, 2018          2007  TV-14   91 min
4903     April 26, 2018          2018  TV-MA   66 min
4999      March 1, 2018          2016  TV-14   94 min
5043   January 31, 2018          2017  TV-PG   96 min
5094  December 27, 2017          2017  TV-14  106 min
5177   November 1, 2017          2016   TV-G   82 min
5293  September 1, 2017          2016  TV-MA   89 min
5512     April 15, 2017          2014  TV-PG   97 min
5513     April 15, 2017          2014  TV-14  105 min
5514     April 15, 2017          2016  TV-14  107 min
5585  February 15, 2017          2015  TV-MA  109 min
5597  February 10, 2017          1977  TV-MA  150 min
5617   January 15, 2017          2008  TV-MA  105 min
5619   January 15, 2017          2014  TV-MA   91 min
5620   January 15, 2017          2014  TV-MA  123 min
5648  December 15, 2016          2015  TV-MA   93 min
5701  November 15, 2016          2016  TV-MA   69 min
6232      March 1, 2017          2013   TV-G   52 min
6531      April 1, 2017          2016  TV-MA   70 min
6621   December 1, 2017          2017  TV-MA   92 min
6709        May 1, 2019          2017  TV-MA   99 min
6778     April 18, 2018          2016      R   92 min
7309      April 9, 2016          2015     NR  116 min
8369     March 15, 2019          2006      R  138 min
8413  December 28, 2016          2016  TV-14   90 min
8426      July 15, 2015          2013      R  155 min

                                              listed_in
705   Documentaries, International Movies, Sports Mo...
1030      Dramas, International Movies, Romantic Movies
1196                                    Stand-Up Comedy
1250                     Comedies, International Movies
1265                    International Movies, Thrillers
1590          Comedies, International Movies, Thrillers
1740                                    Stand-Up Comedy
2053   Dramas, Independent Movies, International Movies
2147                     Comedies, International Movies
2182                 Children & Family Movies, Comedies
2667                       Dramas, International Movies
2772                Documentaries, International Movies
2890   Dramas, Independent Movies, International Movies
2909    Comedies, International Movies, Romantic Movies
3667            Dramas, International Movies, Thrillers
3730               Comedies, Dramas, Independent Movies
3762  Children & Family Movies, Dramas, Internationa...
3767                       Dramas, International Movies
4391                     Comedies, International Movies
4831  Documentaries, International Movies, Sports Mo...
4859                     Comedies, International Movies
4903                                    Stand-Up Comedy
4999                     Comedies, International Movies
5043                Documentaries, International Movies
5094         Children & Family Movies, Music & Musicals
5177                 Children & Family Movies, Comedies
5293  Action & Adventure, Comedies, International Mo...
5512         Children & Family Movies, Music & Musicals
5513         Children & Family Movies, Music & Musicals
5514         Children & Family Movies, Music & Musicals
5585   Dramas, Independent Movies, International Movies
5597                Documentaries, International Movies
5617     Dramas, International Movies, Music & Musicals
5619                    International Movies, Thrillers
5620                       Dramas, International Movies
5648                     Comedies, International Movies
5701                                    Stand-Up Comedy
6232                Documentaries, International Movies
6531   Dramas, Independent Movies, International Movies
6621  Documentaries, International Movies, LGBTQ Movies
6709   Dramas, Independent Movies, International Movies
6778                Horror Movies, International Movies
7309                     Comedies, International Movies
8369            Dramas, International Movies, Thrillers
8413                Documentaries, International Movies
8426   Action & Adventure, Dramas, International Movies

In [41]:
# I
data[['Duration_num', 'Duration_str']] = data['duration'].str.extract(r'(\d+)\s*(\D+)')
data['Duration_num'] = data['Duration_num'].astype(int)
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,Duration_num,Duration_str
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,90,min
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",1,Season
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",1,Season
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, JosÃ© Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,91,min
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",125,min

In [52]:
# J
data = data.drop(columns=['Month', 'Day', 'Year'], errors='ignore')

data['date_added'] = data['date_added'].str.replace(',', '')

split_cols = data['date_added'].str.split(' ', n=2, expand=True)
split_cols.columns = ['Month', 'Day', 'Year']

data = data.join(split_cols)

data['Day'] = pd.to_numeric(data['Day'], errors='coerce')
data['Year'] = pd.to_numeric(data['Year'], errors='coerce')

data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,Duration_num,Duration_str,Month,Day,Year
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,September 25 2021,2020,PG-13,90 min,Documentaries,90,min,September,25.0,2021.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,September 24 2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",1,Season,September,24.0,2021.0
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,September 24 2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",1,Season,September,24.0,2021.0
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, JosÃ© Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,September 24 2021,2021,PG,91 min,Children & Family Movies,91,min,September,24.0,2021.0
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",September 24 2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",125,min,September,24.0,2021.0

In [53]:
# K
year_counts = data['release_year'].value_counts().sort_index()
print(year_counts)

release_year
1942      2
1943      3
1944      3
1945      3
1946      2
       ...
2017    771
2018    757
2019    623
2020    548
2021    297
Name: count, Length: 73, dtype: int64

In [55]:
# L
data=data.rename(columns={'title':'movie_title'})

In [56]:
print(data)

     show_id     type                       movie_title  \
0         s1    Movie              Dick Johnson Is Dead
2         s3  TV Show                         Ganglands
5         s6  TV Show                     Midnight Mass
6         s7    Movie  My Little Pony: A New Generation
7         s8    Movie                           Sankofa
...      ...      ...                               ...
8774   s8802    Movie                           Zinzana
8775   s8803    Movie                            Zodiac
8777   s8805    Movie                        Zombieland
8778   s8806    Movie                              Zoom
8779   s8807    Movie                            Zubaan

                            director  \
0                    Kirsten Johnson
2                    Julien Leclercq
5                      Mike Flanagan
6     Robert Cullen, JosÃ© Luis Ucha
7                       Haile Gerima
...                              ...
8774                 Majid Al Ansari
8775                   David Fincher
8777                 Ruben Fleischer
8778                    Peter Hewitt
8779                     Mozez Singh

                                                   cast  \
0                                                   NaN
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
5     Kate Siegel, Zach Gilford, Hamish Linklater, H...
6     Vanessa Hudgens, Kimiko Glenn, James Marsden, ...
7     Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
...                                                 ...
8774  Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...
8775  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
8777  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
8778  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
8779  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...

                                                country         date_added  \
0                                         United States  September 25 2021
2                                                   NaN  September 24 2021
5                                                   NaN  September 24 2021
6                                                   NaN  September 24 2021
7     United States, Ghana, Burkina Faso, United Kin...  September 24 2021
...                                                 ...                ...
8774                       United Arab Emirates, Jordan       March 9 2016
8775                                      United States   November 20 2019
8777                                      United States    November 1 2019
8778                                      United States    January 11 2020
8779                                              India       March 2 2019

      release_year rating  duration  \
0             2020  PG-13    90 min
2             2021  TV-MA  1 Season
5             2021  TV-MA  1 Season
6             2021     PG    91 min
7             1993  TV-MA   125 min
...            ...    ...       ...
8774          2015  TV-MA    96 min
8775          2007      R   158 min
8777          2009      R    88 min
8778          2006     PG    88 min
8779          2015  TV-14   111 min

                                              listed_in  Duration_num  \
0                                         Documentaries            90
2     Crime TV Shows, International TV Shows, TV Act...             1
5                    TV Dramas, TV Horror, TV Mysteries             1
6                              Children & Family Movies            91
7      Dramas, Independent Movies, International Movies           125
...                                                 ...           ...
8774            Dramas, International Movies, Thrillers            96
8775                     Cult Movies, Dramas, Thrillers           158
8777                            Comedies, Horror Movies            88
8778                 Children & Family Movies, Comedies            88
8779     Dramas, International Movies, Music & Musicals           111

     Duration_str      Month   Day    Year
0             min  September  25.0  2021.0
2          Season  September  24.0  2021.0
5          Season  September  24.0  2021.0
6             min  September  24.0  2021.0
7             min  September  24.0  2021.0
...           ...        ...   ...     ...
8774          min      March   9.0  2016.0
8775          min   November  20.0  2019.0
8777          min   November   1.0  2019.0
8778          min    January  11.0  2020.0
8779          min      March   2.0  2019.0

[6150 rows x 16 columns]

In [57]:
#M
data[['Genre1', 'Genre2', 'Genre3']] = data['listed_in'].str.split(',', n=2, expand=True)

In [58]:
data

,show_id,type,movie_title,director,cast,country,date_added,release_year,rating,duration,listed_in,Duration_num,Duration_str,Month,Day,Year,Genre1,Genre2,Genre3
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,September 25 2021,2020,PG-13,90 min,Documentaries,90,min,September,25.0,2021.0,Documentaries,None,None
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,September 24 2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",1,Season,September,24.0,2021.0,Crime TV Shows,International TV Shows,TV Action & Adventure
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,September 24 2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",1,Season,September,24.0,2021.0,TV Dramas,TV Horror,TV Mysteries
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, JosÃ© Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,September 24 2021,2021,PG,91 min,Children & Family Movies,91,min,September,24.0,2021.0,Children & Family Movies,None,None
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",September 24 2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",125,min,September,24.0,2021.0,Dramas,Independent Movies,International Movies
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8774,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan",March 9 2016,2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",96,min,March,9.0,2016.0,Dramas,International Movies,Thrillers
8775,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,November 20 2019,2007,R,158 min,"Cult Movies, Dramas, Thrillers",158,min,November,20.0,2019.0,Cult Movies,Dramas,Thrillers
8777,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,November 1 2019,2009,R,88 min,"Comedies, Horror Movies",88,min,November,1.0,2019.0,Comedies,Horror Movies,None
8778,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,January 11 2020,2006,PG,88 min,"Children & Family Movies, Comedies",88,min,January,11.0,2020.0,Children & Family Movies,Comedies,None
8779,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,March 2 2019,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",111,min,March,2.0,2019.0,Dramas,International Movies,Music & Musicals

In [140]:
A=pd.read_excel('student.xlsx')

In [141]:
A

     Student_id  Age  Gender      Grade Employed
0             1   19    Male  1st Class      yes
1             2   20  Female  2nd Class       no
2             3   18    Male  1st Class       no
3             4   21  Female  2nd Class       no
4             5   19    Male  1st Class       no
..          ...  ...     ...        ...      ...
227         228   21  Female  1st Class       no
228         229   20    Male  2nd Class       no
229         230   20    Male  3rd Class      yes
230         231   19  Female  1st Class      yes
231         232   20    Male  3rd Class      yes

[232 rows x 5 columns]

In [142]:
B=pd.read_csv('marks.csv')

In [143]:
B

     Student_id  Mark     City
0             1    95  Chennai
1             2    70    Delhi
2             3    98   Mumbai
3             4    75     Pune
4             5    89    Kochi
..          ...   ...      ...
224         228    99     Pune
225         229    70  Chennai
226         230    55    Delhi
227         231    97   Mumbai
228         232    59     Pune

[229 rows x 3 columns]

In [144]:
#A
df=pd.concat([A,B],ignore_index=True)

In [145]:
df

     Student_id   Age  Gender      Grade Employed  Mark     City
0             1  19.0    Male  1st Class      yes   NaN      NaN
1             2  20.0  Female  2nd Class       no   NaN      NaN
2             3  18.0    Male  1st Class       no   NaN      NaN
3             4  21.0  Female  2nd Class       no   NaN      NaN
4             5  19.0    Male  1st Class       no   NaN      NaN
..          ...   ...     ...        ...      ...   ...      ...
456         228   NaN     NaN        NaN      NaN  99.0     Pune
457         229   NaN     NaN        NaN      NaN  70.0  Chennai
458         230   NaN     NaN        NaN      NaN  55.0    Delhi
459         231   NaN     NaN        NaN      NaN  97.0   Mumbai
460         232   NaN     NaN        NaN      NaN  59.0     Pune

[461 rows x 7 columns]

In [72]:
#B
result=df.groupby('Gender')['Mark'].agg(['max','min'])
print(result)

        max  min
Gender
Female  NaN  NaN
Male    NaN  NaN

In [73]:
#C.
average_marks=df['Mark'].mean()

In [74]:
print(average_marks)

71.38864628820961

In [75]:
above_avg_students = df[df['Mark'] > average_marks][['Student_id', 'Mark']]
print(above_avg_students)

     Student_id  Mark
232           1  95.0
234           3  98.0
235           4  75.0
236           5  89.0
241          12  90.0
..          ...   ...
450         222  74.0
451         223  79.0
453         225  72.0
456         228  99.0
459         231  97.0

[137 rows x 2 columns]

In [83]:
#D.
filtered_df = df[(df['Gender'] == 'Male') & (df['Employed'])]
print(filtered_df)

     Student_id   Age Gender      Grade Employed  Mark City
0             1  19.0   Male  1st Class      yes   NaN  NaN
2             3  18.0   Male  1st Class       no   NaN  NaN
4             5  19.0   Male  1st Class       no   NaN  NaN
5             6  20.0   Male  2nd Class      yes   NaN  NaN
7             8  21.0   Male  3rd Class      yes   NaN  NaN
..          ...   ...    ...        ...      ...   ...  ...
224         225  19.0   Male  2nd Class       no   NaN  NaN
226         227  22.0   Male  3rd Class       no   NaN  NaN
228         229  20.0   Male  2nd Class       no   NaN  NaN
229         230  20.0   Male  3rd Class      yes   NaN  NaN
231         232  20.0   Male  3rd Class      yes   NaN  NaN

[136 rows x 7 columns]

In [87]:
df.columns

Index(['Student_id', 'Age', 'Gender', 'Grade', 'Employed', 'Mark', 'City'], dtype='object')

In [91]:
#E.
import numpy as np

df['IQ_level'] = np.where(df['Mark'] > 80, 'Intelligent',
                    np.where(df['Mark'] >= 50, 'Mediocre', 'Weak'))

In [92]:
print(df)

     Student_id   Age  Gender      Grade Employed  Mark     City     IQ_level
0             1  19.0    Male  1st Class      yes   NaN      NaN         Weak
1             2  20.0  Female  2nd Class       no   NaN      NaN         Weak
2             3  18.0    Male  1st Class       no   NaN      NaN         Weak
3             4  21.0  Female  2nd Class       no   NaN      NaN         Weak
4             5  19.0    Male  1st Class       no   NaN      NaN         Weak
..          ...   ...     ...        ...      ...   ...      ...          ...
456         228   NaN     NaN        NaN      NaN  99.0     Pune  Intelligent
457         229   NaN     NaN        NaN      NaN  70.0  Chennai     Mediocre
458         230   NaN     NaN        NaN      NaN  55.0    Delhi     Mediocre
459         231   NaN     NaN        NaN      NaN  97.0   Mumbai  Intelligent
460         232   NaN     NaN        NaN      NaN  59.0     Pune     Mediocre

[461 rows x 8 columns]

In [96]:
#F.
gender_city_counts = df.groupby(['City', 'Gender']).size().unstack(fill_value=0)

print(gender_city_counts)

Empty DataFrame
Columns: []
Index: []

In [104]:
#G.
top_5_Male_scorers = df[df['Gender'] == 'Male'].sort_values(by='Mark', ascending=False).head(5)

print(top_5_Male_scorers)

   Student_id   Age Gender      Grade Employed  Mark City IQ_level
0           1  19.0   Male  1st Class      yes   NaN  NaN     Weak
2           3  18.0   Male  1st Class       no   NaN  NaN     Weak
4           5  19.0   Male  1st Class       no   NaN  NaN     Weak
5           6  20.0   Male  2nd Class      yes   NaN  NaN     Weak
7           8  21.0   Male  3rd Class      yes   NaN  NaN     Weak

In [112]:
#H.
df2= df2['Gender'].replace({'Male': 'M', 'Female': 'F'})
print(df)

0        M
1        F
2        M
3        F
4        M
      ...
456    NaN
457    NaN
458    NaN
459    NaN
460    NaN
Name: Gender, Length: 461, dtype: object

In [116]:
df.to_csv(r'D:\test.csv', index=False)

In [128]:
# I
duplicates = df['Student_id'].duplicated()
print(duplicates)

0      False
1      False
2      False
3      False
4      False
       ...
456     True
457     True
458     True
459     True
460     True
Name: Student_id, Length: 461, dtype: bool

In [129]:
#J
numeric_df = data.select_dtypes(include=['number'])

In [130]:
print(numeric_df)

      release_year  Duration_num   Day    Year
0             2020            90  25.0  2021.0
2             2021             1  24.0  2021.0
5             2021             1  24.0  2021.0
6             2021            91  24.0  2021.0
7             1993           125  24.0  2021.0
...            ...           ...   ...     ...
8774          2015            96   9.0  2016.0
8775          2007           158  20.0  2019.0
8777          2009            88   1.0  2019.0
8778          2006            88  11.0  2020.0
8779          2015           111   2.0  2019.0

[6150 rows x 4 columns]

In [149]:
# K

import pandas as pd


students_df = pd.read_excel("student.xlsx", sheet_name="student")
marks_df = pd.read_excel("Test_file.xlsx", sheet_name="Sheet1")


student_ids_not_in_marks = students_df[~students_df['Student_id'].isin(marks_df['ID'])]


print(student_ids_not_in_marks[['Student_id']])

     Student_id
0             1
1             2
2             3
3             4
4             5
..          ...
227         228
228         229
229         230
230         231
231         232

[227 rows x 1 columns]

#Q.3
1. Concept of Missing Values
Definition:
A missing value occurs when data is not available for a given observation.
2. Identifying Missing Values in Pandas
We can check for missing values using:
import pandas as pd
import numpy as np

# Example DataFrame
data = data = {
    'Name': ['John', 'Sara', 'Mike', None],
    'Age': [25, None, 30, 22],
    'Score': [85, 90, None, 88]
}
df = pd.DataFrame(data)

print(df.isnull())

print(df.isnull().sum())

print(df.isnull().sum().sum())

3. Ways to Handle Missing Values
A. Deleting Missing Values
Remove rows with any missing value

df_dropped_rows = df.dropna()

2.Remove columns with any missing value
  df_dropped_cols = df.dropna(axis=1)

B. Imputing (Filling) Missing Values
Fill with a constant
df_fill_constant = df.fillna(0)

2.Fill with column mean/median/mode

df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Score'].fillna(df['Score'].median(), inplace=True)

3.Forward Fill (fill from previous row)

df_ffill = df.fillna(method='ffill')

4.Backward Fill (fill from next row)

df_bfill = df.fillna(method='bfill')